### ISSUE TITLE
Some reviews imported from productcomments module can't be edited

### ISSUE THREAD

**Issue by getdatakick** [getdatakick/revws#11]
> I just tried to import the old reviews from product_comments module. The import worked, but I face this issue, when I try to approve the reviews: RevwsReview->email is empty.

The root cause is email field being empty

**Comment by SLiCK-303** [comment]
I've noticed the same thing.  Although some can be edited, by butting in an email address, while others just seem to not be editable at all.

**Comment by getdatakick** [comment]
I have made email optional (on backend). Users are still required to fill-in the email on frontend, but it's not hard dependency. Saving / updating reviews without email works just fine now. The only difference is that no email is sent to customer, obviously
