### ISSUE TITLE
URL and translation issues of "My Reviews" page

### ISSUE THREAD

**Issue by FinnenHawke** [getdatakick/revws#111]
I've successfully translated everything to my language (Polish), but I still have a problem with "My Reviews" page in user's area.

First of all, on the breadcrumb, it says "My Reviews", despite this phrase being translated to "Moje opinie" in every possible place in translation settings. How can I change that?

Second of all, I have a problem with URL rewriting. My settings don't seem to take any effect:

"My Reviews" page in User's Area currently has the default URL: **/reviews/my-reviews**
I would like to change it to: **/moje-opinie**

I did that in the Prestashop's URL&SEO preferences, the same way I did with other modules, yet in this case it doesn't seem to take any effect (I cleared and even disabled cache, tried saving changes again and so on).

Screenshot of the URL and "My Reviews" breadcrumb (problem): https://i.imgur.com/wy1mNXy.jpg

Screenshot of the Prestashop's URL settings: https://i.imgur.com/tpdEvA1.jpg

**Comment by getdatakick** [comment]
@FinnenHawke what prestashop version are you using?

**Comment by FinnenHawke** [comment]
@getdatakick PrestaShop 1.7.5.1.

**Comment by getdatakick** [comment]
I can't reproduce this on my ps17 installation -- both translation and url rewrite works ok for me. 

Do you still have this error? If so, please send me email with your domain (and if you could give me access to your back office, it would greatly help)
