### ISSUE TITLE
Pop up to write review bug

### ISSUE THREAD

**Issue by VyckaLTU** [getdatakick/revws#113]
Product image is very big on writing review. Adding picture to show problem.
Prestashop version - prestashop_1.7.3.2

![review](https://user-images.githubusercontent.com/50858450/58070354-6f5fa100-7ba1-11e9-9988-766e5fed6799.png)

**Comment by getdatakick** [comment]
Fixed by 6434680a81627eba4bf5e349be0421a6e229bf1e

**Comment by VyckaLTU** [comment]
It worked. THANK YOU
