### ISSUE TITLE
module is making product horizontal on mobiles 

### ISSUE THREAD

**Issue by fraizor** [getdatakick/revws#122]
after installing the module it is making products look horizontal on mobiles 

see attached image
![Screenshot from 2019-09-28 17-28-14](https://user-images.githubusercontent.com/38109500/65817204-755e3200-e1d2-11e9-9df4-e7bd39565860.png)

**Comment by getdatakick** [comment]
This is theme specific issue. You will need to investigate which css selector is causing this
