### ISSUE TITLE
Controller not found error

### ISSUE THREAD

**Issue by gingerling** [getdatakick/revws#124]
Hi, I downloaded the module from https://store.thirtybees.com/shop-modules/front-office/revws-product-reviews

I upload it, install it and click configure. I see the following page with the error Controller not found 

![Screenshot from 2019-10-09 15-24-43](https://user-images.githubusercontent.com/2853040/66490370-f2c65400-eaa8-11e9-8903-6ce2ea633a21.png)

What do I do to fix? Thanks

**Comment by getdatakick** [comment]
This looks like permission problem. Please check permission settings in `Administration > Permissions`

**Comment by gingerling** [comment]
Don't know about this section, but gave it a shot. Super admin says: 
Administrator permissions cannot be modified. On the other 3 tabs I ticked all boxes for this module, it didn't work. I notice the third box is for "uninstall" - I can do that okay (I reinstalled already)
