### ISSUE TITLE
Failed to send email revws-review-request

### ISSUE THREAD

**Issue by tlukowski** [getdatakick/revws#127]
Hello how can i add 
http://prntscr.com/pw9bpc
for polish language?

I bought premium version and this happend.

**Comment by getdatakick** [comment]
Look into the module support tab, there should be displayed some hint:

![image](https://user-images.githubusercontent.com/34651851/68745475-0eb49c80-05f7-11ea-832e-dc87d9d34307.png)

**Comment by tlukowski** [comment]
Okey thanks. I have 1 more question. How can i change "review your" http://prntscr.com/pwbkie

**Comment by getdatakick** [comment]
See this issue: https://github.com/getdatakick/revws/issues/93
