### ISSUE TITLE
Guest able to write more than one review per product

### ISSUE THREAD

**Issue by SLiCK-303** [getdatakick/revws#13]
If you do a review as a guest, then it gets approved, then you look at the item you reviewed again, you can edit/delete your review. However once you sign in, then sign out, so you’re now a visitor again, and look at that product you reviewed again, you have lost the ability to edit/delete your review. You also now have the ability to write another review.

**Comment by getdatakick** [comment]
I really don't know what to do about this one. My module depends on system to tell retrieve guest id, and when that changes, I just treat it as a new visitor, the same as system does.

IMHO this is a problem in tb core. It should remember guest id and reassign it to visitor when he logged out.

**Comment by SLiCK-303** [comment]
Can you do it will cookie information?  Or is that all done in the core?

**Comment by getdatakick** [comment]
Well, we could remember original visitor id in (encrypted) cookie. I'm not sure if it's worth the trouble, though. What is the benefit?

This wouldn't prevent user from posting multiple reviews. Visitor can simply open incognito window and any client side data will not be available. 

If it's about edit/delete option - maybe we could handle this differently, for example send some _password_ that can be used to obtain edit rights. But again, probably not worth the trouble.

**Comment by SLiCK-303** [comment]
That's a bummer, but I agree, all are not worth the effort.
