### ISSUE TITLE
Could not load content  status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by dandumit** [getdatakick/revws#138]
HEllo,
In console I found this : 

Could not load content for https://www.XXx.XX/modules/revws/views/js/front-2_2_0.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Does it points to a non existent script  ? from where is this included ?

Daniel

**Comment by getdatakick** [comment]
This is not a problem. When you open developer console, browser will find minified javascript file front-2_2_0.js, and then it tries to download source/original/not minified version of this file. This version is not released as part of the module, and therefore this warning is displayed.

It has no functional effect on the module, nor it has any performance impact.
