### ISSUE TITLE
Review popup comes up under theme header

### ISSUE THREAD

**Issue by SLiCK-303** [getdatakick/revws#14]
When you goto My Reviews, or even look at a product, and you’re allll the way to the top of the page, the review popup comes up under the websites header.
![1518893819182capture](https://user-images.githubusercontent.com/763426/36362104-3d62ba0a-14f7-11e8-87fd-bb902aaef9c5.png)
![1518894141037capture](https://user-images.githubusercontent.com/763426/36362105-3f29e4ee-14f7-11e8-9d98-72e0da3834a5.png)

**Comment by getdatakick** [comment]
this is problem with z-index - your theme uses way too high z-index value for header. Unfortunately there isn't any consensus about what z-index value should different UI component use. 

I can increase z-index of review popup

**Comment by SLiCK-303** [comment]
It's a stock z-index from the default ps 1.6 theme, I'm thinking a lot of themes will use it. 5003 does seem a little high though.  :)

**Comment by getdatakick** [comment]
Indeed it is. Unfortunately there's no official guidelines for using z-index. But for content elements I would always use range 1..100, max. Anything over 1000 should be reserved for dynamic stuff like popup, dropdowns etc... 

Well, in version 1.0.4 revws use z-index 1001300, so hopefully that will be enough :)
