### ISSUE TITLE
Read reviews link is broken

### ISSUE THREAD

**Issue by Eitsu** [getdatakick/revws#160]
hello, thanks for this amazing module.
Where can i see All reviews page ? the link in product page does not work. When clicking  "Read one Review", nothing happens. Does anybody know how to fix it?
Thank You!!

**Comment by getdatakick** [comment]
This kind of issue happends when you have some third party 'friendly url' module installed, or when you have some specific .htaccess rules,...

By default, all reviews page is on /reviews url, for example [https://store.getdatakick.com/en/reviews](https://store.getdatakick.com/en/reviews). You can, change the url in your back office SEO & URL page.
