### ISSUE TITLE
Is it posible to hide tab when no reviews?

### ISSUE THREAD

**Issue by therampagerado** [getdatakick/revws#189]
Just updated to 1.3 and I made some css fixes for my design. Excellent as always!

I was wondering if the tab could also be hidden if no reviews are present. Currently on TB when I click on Reviews tab it simply does not open.

![image](https://user-images.githubusercontent.com/11251370/222659751-5b7de2ce-528f-426a-99d7-752f2f40510f.png)

**Comment by getdatakick** [comment]
The tab exists so people could enter new reviews -- there is a button there.

I guess that we could hide the tab, but only if you disable guest reviews, and user is not logged-in.

**Comment by getdatakick** [comment]
Closed by 60eb04ac4948b52e51d4438f6ca7ee92b7826fbb
