### ISSUE TITLE
ThirtyBeesException: Failed to construct service 'revwsemailactionModuleFrontController': This doesn't seem to be a class name: `revwsemailactionModuleFrontController`.

### ISSUE THREAD

**Issue by therampagerado** [getdatakick/revws#191]
Revws version: 2.3.1 (pro version)
TB: edge as of 6.2.2024

EXCEPTION
Message:`
ThirtyBeesException: Failed to construct service 'revwsemailactionModuleFrontController': This doesn't seem to be a class name: revwsemailactionModuleFrontController.`

Location: `classes/core/ServiceLocator.php line 170`

```
#0 classes/core/ServiceLocator.php(170)
#1 classes/core/ServiceLocator.php(112): Thirtybees\Core\DependencyInjection\ServiceLocatorCore->getByServiceName("revwsemailactionModuleFrontController")
#2 classes/Dispatcher.php(845): Thirtybees\Core\DependencyInjection\ServiceLocatorCore->getController("revwsemailactionModuleFrontController")
#3 index.php(33): DispatcherCore->dispatch()
```

Caused by: Core_Foundation_IoC_Exception: This doesn't seem to be a class name: `revwsemailactionModuleFrontController`. at line 183 in file Core/Foundation/IoC/Core_Foundation_IoC_Container.php
Caused by: ReflectionException: Class revwsemailactionModuleFrontController does not exist at line 149 in file Core/Foundation/IoC/Core_Foundation_IoC_Container.php

I have around 40 such errors and I'm unable to find from where they appear as they don't happen daily.

**Comment by getdatakick** [comment]
do you have file `modules/revws/controllers/front/EmailAction.php`, and does it contain this class name?

**Comment by therampagerado** [comment]
Yes,

`class RevwsEmailActionModuleFrontController extends ModuleFrontController`
