### ISSUE TITLE
Share reviews between languages

### ISSUE THREAD

**Issue by therampagerado** [getdatakick/revws#192]
It would be nice if there was a switch that allows sharing reviews between languages.

Currently I have 0 English reviews and some Bulgarian ones. Yes, at first the Bulgarian content in the EN version might be strange but at least it gives some feedback to the customers based on the stars. Additionally if they want to know what is written they can translate the text with just two clicks.

Additionally in this might be helpful if integration with Google Translate API is possible so the cross-language reviews appear in the current shop lang context properly translated (with a notice under every translated review that 'this is machine translation').

**Comment by getdatakick** [comment]
This already exists, see https://store.getdatakick.com/en/support/module/3-revws-product-reviews/303-show-reviews-on-bilingual-site

**Comment by therampagerado** [comment]
Thank you! As always you point my blind eyes to feature you've implemented long ago. :/
