### ISSUE TITLE
DELETE btn btn-primary

### ISSUE THREAD

**Issue by said4440** [getdatakick/revws#28]
hello I want to remove the button because the color of the text and the same as the color of the button.
what is the file that I can edit thanks
![frfr](https://user-images.githubusercontent.com/39734318/40661496-43453d02-6354-11e8-98ab-83a9003d6417.png)

**Comment by getdatakick** [comment]
The easiest way is to use css to either style this button appropriately, or hide it completely. No need to smarty edit templates.

To do this, create (or edit) file

```/themes/<theme>/modules/revws/views/templates/front/css-extend.tpl```

and enter something like this:
```
#idTabRevws .btn {
  display: none;
}
```
or just style it, ie:
```
#idTabRevws .btn {
  color: black;
  background-color: white;
}
```

**Comment by said4440** [comment]
thank you very much for your speed
