### ISSUE TITLE
TB1.0.5 - Warehouse theme (v.latest.for.PS.1.6) - there's no review tab, just a button under the current tab

### ISSUE THREAD

**Issue by therampagerado** [getdatakick/revws#31]
There is no review tab. The tab is rendered but when I click on it it scrolls down instead of opening the tab.

It scrolls down using the current tab and there's the button 'be the first to write a review).

I'm using TB and Warehouse for PS1.6.
![image](https://user-images.githubusercontent.com/11251370/42419220-df6fcb60-82b8-11e8-9ef5-3cd5a1c9787e.png)
![image](https://user-images.githubusercontent.com/11251370/42419224-ed26c81c-82b8-11e8-89ae-0477cd00c9b0.png)

**Comment by getdatakick** [comment]
This seems to be theme (warehouse) issue, there's not much I can do about it. Tabs work correctly on standard ps16 (and thirtybees) theme
