### ISSUE TITLE
Additional strings for when there's only 1 review in PRODUCT_BUTTONS and PRODUCT_EXTRA

### ISSUE THREAD

**Issue by therampagerado** [getdatakick/revws#34]
When we have only one review for a product the current setup shows "(read 1 reviews)". If we write multiple reviews it's OK but the current translation is wrong for when there's only one review.

It should be: "stars here" (read 1 review) OR (read 3 reviews)

![image](https://user-images.githubusercontent.com/11251370/42419656-29f430aa-82c2-11e8-9e1c-048fab8a9817.png)

**Comment by therampagerado** [comment]
Thank you! Looking forward to the new release!

**Comment by getdatakick** [comment]
@therampagerado  happy to help. If you could send me translation for both singular and plural version of the new string, I'd be very grateful!

**Comment by therampagerado** [comment]
In Bulgarian:

- singular - прочети 1 ревю
- plural - прочети N ревюта
