### ISSUE TITLE
Multistore Bugs on Reviews Page

### ISSUE THREAD

**Issue by eschiendorfer** [getdatakick/revws#68]
Recently I updated the module, to the newest version. Now I have a lot of errors in my SEO tool. The reason is, that the /reviews page is not multistore ready. All reviews are listed there, not only the ones with the product of a certain shop.

**Comment by getdatakick** [comment]
Thanks for reporting this. I've added fix, will be part of next release.

I'm still need to implement proper multistore support, though. At the moment reviews are shared across all shops. This is probably what most of the people want, but I'm sure there is someone who don't want this behavior.
