### ISSUE TITLE
Issue on front office product with PS 1.7.4

### ISSUE THREAD

**Issue by Erwax** [getdatakick/revws#77]
<img width="307" alt="capture d ecran 2018-10-21 a 23 33 18" src="https://user-images.githubusercontent.com/7267774/47272771-9bbf2a80-d58a-11e8-8b83-2c70cb31e986.png">

PrestaShop version: 1.7.4.3
Revws - Product Reviews: v1.0.21

Default configuration / installation of PrestaShop, no additional modules or themes.

**Comment by getdatakick** [comment]
Hi, 

unfortunately this is theme issue. In this case it's standard theme, but nevertheless it's theme problem - theme calls hook to render stars, but do not reserve enough space to render the ratings. 

The same issue can be reproduced with other modules as well, for example `productcomments` module. 

The fix should be made in theme css
