### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by cgodefroy** [getdatakick/revws#83]
I'd like to contribute a French translation, but there's no info on how to do it nor patch keys. And there is no translations/en.php…
A little help would be helpful.

**Comment by getdatakick** [comment]
Hi, thank you for your pending contribution. 

You can either:
1) export you translation from prestashop using standard translation tool, and send me the exported file. I will convert it to json file (below)
2) or clone this repository, copy file [translations/en.json](https://github.com/getdatakick/revws/blob/ps16/translations/en.json) to `translations/fr.json`, and enter your translation strings there. Please refer to [german](https://github.com/getdatakick/revws/blob/ps16/translations/de.json) translation for reference. Then you can create pull request for me to merge your changes

Also, it would be awesome if you could do the same with email templates. In this case, copy directory [/php/mails/en](https://github.com/getdatakick/revws/tree/ps16/php/mails/en) to `/php/mails/fr` and edit content of email templates.
