### ISSUE TITLE
mail subjects without translations

### ISSUE THREAD

**Issue by helpman** [getdatakick/revws#93]
When you send an email, no matter if the language is set to spanish, the emails received displays the subjects in english. I can't find find anywhere to translate them

**Comment by getdatakick** [comment]
Email subjects can be translated using standard prestashop / thirtybees functionality:

#### Change subject in `Localization > Translations > Email templates translations`

<img width="500" alt="subject" src="https://user-images.githubusercontent.com/34651851/50882852-77832500-13e6-11e9-8c52-234f67b8cb12.png">

#### Email log showing that translated subject is used

<img width="500" alt="subject2" src="https://user-images.githubusercontent.com/34651851/50882924-b4e7b280-13e6-11e9-9afa-6327674844b3.png">

**Comment by helpman** [comment]
thanks! I was going mad trying to find it inside the module's translation
